### ISSUE TITLE
Unwanted tile spacing issues after css board rotation.

### ISSUE THREAD

**Issue by Vlakoosh** [Vlakoosh/js-chess#1]
# issue
Whenever the board rotates _back_ to white, a little 1px space appears between the tiles/squares in a weird 3x3 grid. I have no idea what causes it, nor how to fix it. 

## how to replicate bug
Make a move as white, then a move as black. When it's white turn again, you should be able to see spaces between squares in a 3x3 grid offset by 2 squares.
The unwanted spacing is more visible when you change the background color of #gameboard to black.

## possible cause
The issue seems to be caused by the setTileRotationReverse() and setTileRotationRegular() functions.

**Comment by AnukratiMehta** [comment]
@Vlakoosh I could not see the bug when I followed your instructions to replicate it. Can you add screenshots?

**Comment by Vlakoosh** [comment]
@AnukratiMehta yes, of course. With the current version you should be able to replicate it. I use firefox to open up the html file. 
![image](https://github.com/Vlakoosh/js-chess/assets/68621923/c0b89d11-d5b4-4b4e-8e1e-f80510c8eaad)
![image](https://github.com/Vlakoosh/js-chess/assets/68621923/e080c4d1-3f78-4c31-9c17-1ab9a41f83f1)

**Comment by Vlakoosh** [comment]
It seems to be a browser specific issue rather than a code problem. It works fine on Chrome and Opera, but is broken on Firefox and Edge. It's a real front end development moment
